// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnykgQxD5qva6usWdmuzsPqktzlkgxsa0',
    appId: '1:376068711995:android:f07b1cfe282db511b6de1e',
    messagingSenderId: '376068711995',
    projectId: 'offcourse-a54c2',
    storageBucket: 'offcourse-a54c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHarNYV7rnMwThhVIO_u35Q_WrS7It9s',
    appId: '1:376068711995:ios:93a66779edaaefabb6de1e',
    messagingSenderId: '376068711995',
    projectId: 'offcourse-a54c2',
    storageBucket: 'offcourse-a54c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoHuD_EdhF5mV4zajReJ63hx6ysIbQgT4',
    appId: '1:376068711995:web:dbc67ac52f138055b6de1e',
    messagingSenderId: '376068711995',
    projectId: 'offcourse-a54c2',
    authDomain: 'offcourse-a54c2.firebaseapp.com',
    storageBucket: 'offcourse-a54c2.firebasestorage.app',
    measurementId: 'G-DS8EQ5YLRL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHarNYV7rnMwThhVIO_u35Q_WrS7It9s',
    appId: '1:376068711995:ios:93a66779edaaefabb6de1e',
    messagingSenderId: '376068711995',
    projectId: 'offcourse-a54c2',
    storageBucket: 'offcourse-a54c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoHuD_EdhF5mV4zajReJ63hx6ysIbQgT4',
    appId: '1:376068711995:web:bc5fe00de27a7077b6de1e',
    messagingSenderId: '376068711995',
    projectId: 'offcourse-a54c2',
    authDomain: 'offcourse-a54c2.firebaseapp.com',
    storageBucket: 'offcourse-a54c2.firebasestorage.app',
    measurementId: 'G-MKFE926305',
  );

}